import { createBrowserP01Journey } from './src/p01/browser-journey.mjs';

const app=document.querySelector('#app');
let controller; let busy=false;
const stageOrder=['ENTRY','ASSESSMENT','CONTROL_MAP','L01','REFLECTION','MAP_UPDATE','L02','REFLECTION','MAP_UPDATE','NEXT_STEP','PRACTICE','PRACTICE_RESULT','SAFETY_GUIDANCE','OFFER'];
const labels={ENTRY:'Entrada',ASSESSMENT:'Avaliação',CONTROL_MAP:'Mapa',L01:'L01',REFLECTION:'Reflexão',MAP_UPDATE:'Mapa',L02:'L02',NEXT_STEP:'Próximo passo',PRACTICE:'Prática',PRACTICE_RESULT:'Resultado',SAFETY_GUIDANCE:'Segurança',OFFER:'Oferta'};
const dimensionNames={bodyAwareness:'Consciência corporal',arousalAwareness:'Consciência de excitação',selfRegulation:'Autorregulação',mentalAttention:'Atenção mental',emotionalResponse:'Resposta emocional',contextCommunication:'Contexto e comunicação',perceivedConfidence:'Confiança percebida'};
const stageIndex=phase=>Math.max(0,stageOrder.indexOf(phase));
const button=(label,action,kind='')=>`<button class="${kind}" data-action="${action}">${label}</button>`;
const shell=content=>{app.innerHTML=`<header class="topbar"><div class="brand">CUM.G</div><div class="privacy">Educação • Privacidade por design</div></header><section class="container">${content}<div class="footer">Conteúdo educacional. Não substitui avaliação profissional. Dados íntimos não são exibidos nesta superfície.</div></section>`};
const progress=state=>{const i=stageIndex(state.phase);const pct=Math.max(4,Math.round((i/(stageOrder.length-1))*100));return `<div class="progress-wrap"><span class="progress-label">${labels[state.phase]??state.phase}</span><span class="progress-label">${pct}%</span></div><div class="progress" aria-label="Progresso da jornada"><span style="width:${pct}%"></span></div>`};
const stageView=state=>`<div class="stage">${stageOrder.map((s,i)=>`<span class="${i===stageIndex(state.phase)?'active':''}">${labels[s]}</span>`).join('')}</div>`;
const dispatch=async event=>{if(busy)return;busy=true;render();try{await controller.journey.dispatch({...event,userId:controller.userId});}finally{busy=false;render()}};
function render(){if(!controller){shell('<div class="card"><h2>Carregando CUM.G…</h2><p class="muted">Carregando os contratos canônicos do P01.</p></div>');return;}const state=controller.journey.getState();let body='';
if(state.phase==='ENTRY')body=`<div class="hero"><div class="eyebrow">V0.1 • Educação</div><h1>Controle Ejaculatório</h1><p>Uma jornada educacional para observar padrões, aprender princípios e construir próximos passos com segurança.</p></div><div class="card"><h2>Antes de começar</h2><p class="muted">A experiência exige confirmação de maioridade. A confirmação é versionada e o conteúdo educacional não depende de uma compra.</p><div class="actions">${button(busy?'Preparando…':'Sou maior de 18 anos','consent')}</div></div>`;
else if(state.phase==='ASSESSMENT'){const q=state.assessmentState?.instrument?.questions?.find(x=>x.code===state.assessmentState.queue?.[0]);if(!q)body=`<div class="card"><h2>Preparando avaliação…</h2></div>`;else body=`<div class="card"><div class="eyebrow">Avaliação ${state.assessmentState.answeredQuestionCodes.length+1}</div><h2>Vamos observar seu contexto</h2><p class="question">${q.purpose.replaceAll('_',' ')}</p><div class="options">${[0,1,2,3,4].map(v=>`<button class="option" data-answer="${v}" ${busy?'disabled':''}>${v}</button>`).join('')}</div><div class="status-line"><span class="status-dot"></span>Instrumento ${state.assessmentState.instrumentVersion} • até 32 respostas</div></div>`;}
else if(state.phase==='CONTROL_MAP')body=mapCard(state,'Seu Mapa de Controle',button('Começar L01','l01'));
else if(state.phase==='L01'||state.phase==='L02'){const lesson=controller.lessons[state.currentLessonCode];const player=controller.players[state.currentLessonCode];const block=lesson?.blocks?.find(x=>x.stage===state.lessonState?.currentStage);const p=player?.getState();body=`<div class="card">${stageView(state)}<div class="eyebrow">${state.currentLessonCode} • ${block?.stage??'CONCLUÍDO'}</div><h2>${block?.contentKey??'Lição concluída'}</h2><p class="muted">Proveniência: ${block?.provenanceClass??'—'}.</p>${block?.claimRefs?.length?`<p class="muted">Base documentada: ${block.claimRefs.length} referência(s).</p>`:''}${block?.nonSexual?'<div class="notice">Prática inicial não sexual: atenção à respiração e à tensão corporal, sem forçar.</div>':''}<div class="status-line"><span class="status-dot"></span>Player ${p?.status??'READY'} • etapa ${Math.min((p?.index??0)+1,p?.total??lesson.blocks.length)} de ${p?.total??lesson.blocks.length}</div><div class="actions">${button(busy?'Salvando…':block?'Concluir etapa':'Concluir lição','lesson-next')}</div></div>`;}
else if(state.phase==='REFLECTION')body=`<div class="card"><div class="eyebrow">Reflexão privada</div><h2>Faça uma pausa para refletir</h2><p class="muted">A superfície não coleta texto íntimo. Na arquitetura completa, a reflexão pertence ao Vault privado.</p><div class="notice">Nenhum conteúdo privado é enviado para analytics ou publicidade.</div><div class="actions">${button('Continuar','reflection')}</div></div>`;
else if(state.phase==='MAP_UPDATE')body=mapCard(state,'Atualização do mapa',state.currentLessonCode==='P01-L01'?button('Continuar para L02','l02'):button('Encontrar próximo passo','next'));
else if(state.phase==='NEXT_STEP')body=`<div class="card"><div class="eyebrow">Próximo passo</div><h2>Prática educacional progressiva</h2><p>O motor de recomendação selecionou o próximo exercício a partir do estado educacional.</p><div class="actions">${button('Resolver próximo passo','resolve')}</div></div>`;
else if(state.phase==='PRACTICE'){const pp=controller.getPracticePlayer()?.presentation();const started=pp?.status==='IN_PROGRESS';body=`<div class="card"><div class="eyebrow">Prática guiada</div><h2>Prática educacional progressiva</h2><p class="muted">Exercício ${pp?.targetId??'selecionado pelo motor'} • dimensão ${dimensionNames[pp?.dimension]??pp?.dimension??'educacional'}</p><div class="notice">Observe um sinal de contexto, nomeie o estado atual e mude a atenção suavemente. Sem forçar.</div><div class="progress-wrap"><span class="progress-label">Etapas</span><span class="progress-label">${pp?.completedSteps??0}/3</span></div><div class="progress"><span style="width:${pp?.progress??0}%"></span></div><div class="actions">${button(busy?'Processando…':started?'Concluir 3 etapas':'Iniciar','practice-action')}</div></div>`;}
else if(state.phase==='PRACTICE_RESULT')body=`<div class="card"><div class="eyebrow">Resultado</div><h2>Prática concluída</h2><p>O resultado pode ser incorporado ao mapa sem expor texto íntimo.</p><div class="actions">${button('Registrar resultado e atualizar mapa','practice-result')}</div></div>`;
else if(state.phase==='SAFETY_GUIDANCE')body=`<div class="card safety"><div class="eyebrow">Segurança primeiro</div><h2>Orientação de segurança</h2><p>A orientação de segurança é resolvida antes de qualquer prática ou oferta e não fica atrás de paywall.</p><div class="notice">${state.safetyGuidance?.guidanceKey??'P01.SAFETY'}</div><div class="actions">${button('Continuar','safety')}</div></div>`;
else if(state.phase==='OFFER')body=`<div class="card"><div class="eyebrow">FREE concluído</div><h2>Jornada educacional concluída</h2><p>O valor educacional gratuito foi entregue antes desta etapa. A oferta é separada da orientação de segurança e não é persistida como checkpoint.</p><div class="actions">${button('Ver opções','offer')}</div></div>`;
else if(state.phase==='ERROR')body=`<div class="card safety"><h2>Jornada interrompida com segurança</h2><p>${state.error}</p><p class="muted">Nenhuma oferta foi exibida.</p></div>`;
shell(progress(state)+body);}
function mapCard(state,title,action){const map=state.controlMap;return `<div class="card"><div class="eyebrow">${title}</div><h2>Mapa de Controle</h2><p class="muted">Sete dimensões educacionais. Não é diagnóstico nem nota clínica.</p><div class="map">${Object.entries(map?.dimensions??{}).map(([k,v])=>`<div class="dimension"><b>${dimensionNames[k]??k}</b><span class="muted">${v.value}%</span><div class="meter"><span style="width:${Math.max(0,Math.min(100,v.value))}%"></span></div></div>`).join('')}</div><div class="actions">${action}</div></div>`;}
app.addEventListener('click',async e=>{const action=e.target.dataset.action;if(e.target.dataset.answer!==undefined){await dispatch({type:'ANSWER_ASSESSMENT',input:{questionCode:controller.journey.getState().assessmentState.queue[0],value:Number(e.target.dataset.answer)}});return;}if(!action)return;if(action==='consent')await dispatch({type:'CONFIRM_ADULT_CONSENT',input:{ageConfirmed:true}});else if(action==='l01'){await dispatch({type:'BUILD_CONTROL_MAP'});await dispatch({type:'START_L01',lesson:controller.lessons['P01-L01']});const p=controller.players['P01-L01'];if(p.getState().status==='READY')p.start();render();}else if(action==='lesson-next'){const s=controller.journey.getState();const p=controller.players[s.currentLessonCode];if(p.getState().status==='READY')p.start();p.completeStage();await dispatch({type:s.phase==='L01'?'ADVANCE_L01':'ADVANCE_L02',input:{stage:s.lessonState.currentStage,completed:true}});}else if(action==='reflection')await dispatch({type:'SAVE_REFLECTION',privateRecord:{kind:'REFLECTION_NOT_COLLECTED'}});else if(action==='l02'){await dispatch({type:'START_L02',lesson:controller.lessons['P01-L02']});const p=controller.players['P01-L02'];if(p.getState().status==='READY')p.start();render();}else if(action==='next')await dispatch({type:'RESOLVE_NEXT_STEP',safetyInput:{privateSignals:{}}});else if(action==='resolve')await dispatch({type:'START_PRACTICE'});else if(action==='practice-action'){const p=controller.getPracticePlayer();if(!p)await dispatch({type:'START_PRACTICE'});else if(p.getState().status==='READY'){p.start();render();}else await dispatch({type:'COMPLETE_PRACTICE',input:{completedSteps:3,reflectionRecorded:false}});}else if(action==='practice-result'){await dispatch({type:'SAVE_PRACTICE_RESULT',privateRecord:{kind:'PRACTICE_RESULT_NOT_COLLECTED'}});await dispatch({type:'UPDATE_PRACTICE_MAP',controlMap:controller.updateMap('mentalAttention',50)});}else if(action==='safety')await dispatch({type:'VIEW_OFFER',showOffer:false});else if(action==='offer')await dispatch({type:'VIEW_OFFER',showOffer:true});});
(async()=>{try{controller=await createBrowserP01Journey({userId:'browser-demo'});render();}catch(error){shell(`<div class="card safety"><h2>Não foi possível carregar o P01</h2><p>${error.message}</p></div>`);}})();
