const app=document.querySelector('#app');
const stages=['entry','age-consent','assessment','control-map','p01-l01','reflection','map-update','p01-l02','reflection-2','map-update-2','next-step','practice','practice-result','safety-guidance','offer'];
const dimensions=[['Consciência corporal','Percepção e observação'],['Padrões','Contexto e variação'],['Atenção','Foco e mudança de atenção'],['Comunicação','Expectativas e registro'],['Contexto','Situações e sinais'],['Prática','Aprendizagem gradual'],['Reflexão','Escolhas e próximos passos']];
const lessonStages=['LEARN','OBSERVE','PRACTICE','RECORD','REFLECT','COMPARE','ADVANCE'];
let state={stage:0,answers:0,lessonStage:0,lesson:1,map:false,reflection:false,practice:false,safety:false};
const current=()=>stages[state.stage];
function shell(content){app.innerHTML=`<header class="topbar"><div class="brand">CUM.G</div><div class="privacy">Educação • Privacidade por design</div></header><section class="container">${content}<div class="footer">Conteúdo educacional. Não substitui avaliação profissional. Dados íntimos não são exibidos nesta superfície.</div></section>`}
function progress(){return `<div class="progress"><span style="width:${Math.max(4,Math.round((state.stage/(stages.length-1))*100))}%"></span></div>`}
function stagesView(){return `<div class="stage">${stages.map((s,i)=>`<span class="${i===state.stage?'active':''}">${s.replaceAll('-',' ')}</span>`).join('')}</div>`}
function button(label,action,kind=''){return `<button class="${kind}" data-action="${action}">${label}</button>`}
function render(){const s=current();let body='';if(s==='entry')body=`<div class="hero"><div class="eyebrow">V0.1 • Educação</div><h1>Controle Ejaculatório</h1><p>Uma jornada educacional para observar padrões, aprender princípios e construir próximos passos com segurança. A experiência começa gratuitamente.</p></div><div class="card"><h2>Antes de começar</h2><p class="muted">Você precisa confirmar que é maior de 18 anos. A confirmação é versionada e não libera conteúdo premium.</p>${button('Sou maior de 18 anos','consent')}</div>`;
else if(s==='age-consent')body=`<div class="card"><div class="eyebrow">Consentimento</div><h2>Entrada protegida</h2><p>Confirme para continuar. Se não puder confirmar, a jornada permanece bloqueada.</p>${button('Confirmar e iniciar','consent-ok')}${button('Voltar','back','secondary')}</div>`;
else if(s==='assessment')body=`<div class="card"><div class="eyebrow">Avaliação educacional</div><h2>Vamos começar pelo seu contexto</h2><p class="question">Qual aspecto você percebe como mais importante observar primeiro?</p><div class="options">${['Consciência corporal','Padrões e contexto','Atenção','Expectativas'].map((x,i)=>`<button class="option" data-answer="${i}">${x}</button>`).join('')}</div><p class="muted">Perguntas adaptativas: o instrumento tem 12 questões centrais e limite máximo de 32 respostas.</p></div>`;
else if(s==='control-map')body=`<div class="card"><div class="eyebrow">Seu mapa educacional</div><h2>Mapa de Controle</h2><p class="muted">Sete dimensões para organizar aprendizado. Isto não é diagnóstico nem uma nota de desempenho.</p><div class="map">${dimensions.map(([a,b])=>`<div class="dimension"><b>${a}</b><span class="muted">${b}</span></div>`).join('')}</div>${button('Começar L01','l01')}</div>`;
else if(s==='p01-l01'||s==='p01-l02'){const lesson=state.lesson===1?'L01':'L02';const texts=lesson==='L01'?['Entender variabilidade de resposta.','Observar padrões sem julgamento.','Praticar atenção corporal neutra.','Registrar uma observação.','Refletir sobre atenção.','Comparar expectativa e experiência.','Avançar para o próximo passo.']:['Entender padrões contextuais.','Observar sinais de contexto.','Praticar mudança suave de atenção.','Registrar contexto.','Refletir sobre um ponto de escolha.','Comparar expectativa e contexto.','Avançar para o próximo passo.'];body=`<div class="card">${stagesView()}<div class="eyebrow">P01-${lesson} • ${lessonStages[state.lessonStage]}</div><h2>${texts[state.lessonStage]}</h2><p class="muted">Fonte do bloco: ${state.lessonStage%3===0?'SCIENTIFIC':state.lessonStage%3===1?'EXPERIENTIAL':'HNK'}.</p>${state.lessonStage===2?'<div class="notice">Prática inicial não sexual: observe a respiração e a tensão corporal sem forçar nada; retorne a atenção suavemente.</div>':''}${button(state.lessonStage<6?'Continuar':'Concluir lição',state.lessonStage<6?'lesson-next':'lesson-done')}</div>`}
else if(s==='reflection'||s==='reflection-2')body=`<div class="card"><div class="eyebrow">Reflexão privada</div><h2>O que você percebeu?</h2><p class="muted">Na aplicação completa, este registro pertence ao Vault privado. Esta demonstração não coleta o texto.</p><div class="notice">Sua reflexão não é transformada em dado genérico de analytics ou publicidade.</div>${button('Continuar sem registrar texto','reflection-done')}</div>`;
else if(s.startsWith('map-update'))body=`<div class="card"><div class="eyebrow">Atualização do mapa</div><h2>Aprendizado incorporado</h2><p>O mapa recebe a nova etapa de aprendizado antes de liberar o próximo passo.</p>${button(state.lesson===1?'Continuar para L02':'Encontrar próximo passo',state.lesson===1?'l02':'next')}</div>`;
else if(s==='next-step')body=`<div class="card"><div class="eyebrow">Próximo passo</div><h2>Prática educacional</h2><p>O próximo exercício é progressivo, não sexual e orientado à atenção e observação.</p>${button('Iniciar prática','practice')}</div>`;
else if(s==='practice')body=`<div class="card"><div class="eyebrow">Prática</div><h2>Prática guiada</h2><div class="notice">Observe um sinal de contexto, nomeie seu estado atual e mude a atenção suavemente. Sem forçar.</div>${button('Concluir prática','practice-done')}</div>`;
else if(s==='practice-result')body=`<div class="card"><div class="eyebrow">Resultado</div><h2>Prática concluída</h2><p>Você pode registrar uma reflexão privada antes de atualizar o mapa.</p>${button('Atualizar mapa','practice-map')}</div>`;
else if(s==='safety-guidance')body=`<div class="card safety"><div class="eyebrow">Segurança primeiro</div><h2>Orientação de segurança</h2><p>Foi identificado um sinal que exige orientação de segurança antes de qualquer prática ou oferta. A orientação não fica atrás de paywall.</p>${button('Entendi','safety-done')}</div>`;
else if(s==='offer')body=`<div class="card"><div class="eyebrow">Próximo nível</div><h2>Você concluiu a jornada FREE</h2><p>O conteúdo educacional gratuito foi entregue antes desta etapa. Qualquer oferta é separada da orientação de segurança e não é persistida como checkpoint.</p>${button('Ver opções','offer-view')}${button('Voltar ao mapa','restart','secondary')}</div>`;
 shell(progress()+body)}
app.addEventListener('click',e=>{const a=e.target.dataset.action;if(!a)return;if(a==='consent'){state.stage=1}else if(a==='consent-ok'){state.stage=2}else if(a==='back'){state.stage=Math.max(0,state.stage-1)}else if(a==='l01'){state.lesson=1;state.lessonStage=0;state.stage=4}else if(a==='lesson-next'){state.lessonStage++;render();return}else if(a==='lesson-done'){state.stage=state.lesson===1?5:8;state.lessonStage=0}else if(a==='reflection-done'){state.stage=state.lesson===1?6:9}else if(a==='l02'){state.lesson=2;state.lessonStage=0;state.stage=7}else if(a==='next'){state.stage=10}else if(a==='practice'){state.stage=11}else if(a==='practice-done'){state.stage=12}else if(a==='practice-map'){state.stage=13}else if(a==='safety-done'){state.stage=14}else if(a==='offer-view'){state.stage=14}else if(a==='restart'){state={stage:2,answers:0,lessonStage:0,lesson:1,map:false,reflection:false,practice:false,safety:false}}render()});
app.addEventListener('click',e=>{if(e.target.dataset.answer!==undefined){state.answers++;state.stage=3;render()}});render();
