import test from 'node:test';
import assert from 'node:assert/strict';
import { createP01FreeJourney } from '../../apps/web/src/p01/free-journey.mjs';

function createDeps(overrides={}) {
  return {
    consentGate: (input) => input?.allowed === true ? {allowed:true,reason:'ALLOWED'} : {allowed:false,reason:'CONSENT_REQUIRED'},
    assessment: { start: () => ({status:'IN_PROGRESS',assessmentId:'assessment-1',instrumentCode:'P01',instrumentVersion:'1.0.0',answers:{}}), answer: (state,input) => ({...state,answers:{...state.answers,[input.code]:input.value},status:input.complete?'COMPLETE':'IN_PROGRESS'}) },
    controlMap: { build: () => ({status:'COMPLETE',version:1,dimensions:{bodyAwareness:{value:50}}}) },
    lesson: { create: () => ({status:'IN_PROGRESS',currentStage:'LEARN'}), advance: (state,input) => input.final ? {...state,status:'COMPLETE'} : {...state,currentStage:input.nextStage} },
    safety: { evaluate: (input) => input?.urgent ? {escalated:true,guidanceKey:'P01.SAFETY.URGENT_CARE',ruleId:'SAFETY-URGENT'} : {escalated:false} },
    recommendation: { next: () => ({kind:'EXERCISE',targetId:'P01-PRACTICE-02',ruleId:'NEXT-PROGRESSIVE',explanationKey:'P01.NEXT.PROGRESSIVE_PRACTICE'}) },
    entitlement: { evaluate: () => ({allowed:false,reason:'PREMIUM_REQUIRED'}) }, analytics:()=>{},
    practiceRuntime: { create: ({recommendation}) => ({status:'READY',start:()=>({status:'IN_PROGRESS'}),complete:()=>({status:'COMPLETE',targetId:recommendation.targetId})}) },
    controlMapHistory: { saveSnapshot:async(input)=>({id:'map-'+(input.map.version??1)}),loadLatestSnapshot:async()=>null },
    journeyCheckpoint: { save:async()=>({id:'checkpoint',state_version:1}), loadLatest:async()=>null },
    ...overrides,
  };
}

async function reachMapUpdate(j){ await j.dispatch({type:'CONFIRM_ADULT_CONSENT',input:{allowed:true}});await j.dispatch({type:'START_ASSESSMENT'});await j.dispatch({type:'ANSWER_ASSESSMENT',input:{code:'P01Q01',value:4,complete:true}});await j.dispatch({type:'BUILD_CONTROL_MAP',userId:'user-1'});await j.dispatch({type:'START_L01',lesson:{},userId:'user-1'});await j.dispatch({type:'ADVANCE_L01',input:{final:true},userId:'user-1'});await j.dispatch({type:'SAVE_REFLECTION',privateRecord:{kind:'L01'},userId:'user-1'});await j.dispatch({type:'UPDATE_MAP',controlMap:{status:'COMPLETE',dimensions:{}},userId:'user-1'});await j.dispatch({type:'START_L02',lesson:{},userId:'user-1'});await j.dispatch({type:'ADVANCE_L02',input:{final:true},userId:'user-1'});await j.dispatch({type:'SAVE_REFLECTION',privateRecord:{kind:'L02'},userId:'user-1'});await j.dispatch({type:'UPDATE_MAP',controlMap:{status:'COMPLETE',dimensions:{}},userId:'user-1'});await j.dispatch({type:'RESOLVE_NEXT_STEP',safetyInput:{},userId:'user-1'});await j.dispatch({type:'START_PRACTICE',userId:'user-1'});await j.dispatch({type:'COMPLETE_PRACTICE',userId:'user-1'});return j.dispatch({type:'SAVE_PRACTICE_RESULT',privateRecord:{kind:'PRACTICE'},userId:'user-1'}); }

test('adult synthetic user completes FREE journey and receives value before offer',async()=>{const j=createP01FreeJourney(createDeps());const recorded=await reachMapUpdate(j);assert.equal(recorded.phase,'MAP_UPDATE');const offered=await j.dispatch({type:'UPDATE_PRACTICE_MAP',userId:'user-1',controlMap:{status:'COMPLETE',version:2,dimensions:{}}});assert.equal(offered.phase,'OFFER');assert.equal(offered.offerVisible,true);});

test('safety guidance wins over premium gate and remains available before offer',async()=>{const j=createP01FreeJourney(createDeps());await reachMapUpdate(j);const state=await j.dispatch({type:'UPDATE_PRACTICE_MAP',userId:'user-1',controlMap:{status:'COMPLETE',version:2,dimensions:{}}});assert.equal(state.phase,'OFFER');const result=await j.dispatch({type:'VIEW_OFFER',showOffer:true,entitlementInput:{resourceTier:'PREMIUM'}});assert.equal(result.offerVisible,true);});

test('bootstrap prefers granular checkpoint and resumes exact lesson stage',async()=>{const checkpoint={phase:'L02',controlMap:{status:'COMPLETE',version:1,dimensions:{}},lessonState:{status:'IN_PROGRESS',currentStage:'PRACTICE'},currentLessonCode:'P01-L02',completedLessons:['P01-L01'],reflections:[{lessonCode:'P01-L01',record:{kind:'L01'}}],freeValueDelivered:true,mapHistory:[{version:1,status:'SAVED',id:'map-1'}]};const j=createP01FreeJourney(createDeps({journeyCheckpoint:{save:async()=>({id:'c'}),loadLatest:async({userId})=>{assert.equal(userId,'user-1');return {state:checkpoint,stateVersion:4};}}}));const state=await j.dispatch({type:'BOOTSTRAP_SESSION',userId:'user-1'});assert.equal(state.phase,'L02');assert.equal(state.lessonState.currentStage,'PRACTICE');assert.equal(state.currentLessonCode,'P01-L02');assert.deepEqual(state.completedLessons,['P01-L01']);assert.equal(state.checkpointVersion,4);assert.equal(state.offerVisible,false);});

test('bootstrap falls back to latest map when no granular checkpoint exists',async()=>{const recovered={status:'COMPLETE',version:2,dimensions:{}};const j=createP01FreeJourney(createDeps({controlMapHistory:{saveSnapshot:async()=>({id:'x'}),loadLatestSnapshot:async()=>({id:'map-2',version:2,map:recovered})}}));const state=await j.dispatch({type:'BOOTSTRAP_SESSION',userId:'u'});assert.equal(state.phase,'NEXT_STEP');assert.deepEqual(state.controlMap,recovered);});

test('checkpoint persistence failure fails closed before advancing lesson stage',async()=>{const j=createP01FreeJourney(createDeps({journeyCheckpoint:{loadLatest:async()=>null,save:async()=>{throw new Error('CHECKPOINT_WRITE_FAILED');}}}));await j.dispatch({type:'CONFIRM_ADULT_CONSENT',input:{allowed:true}});const state=await j.dispatch({type:'START_ASSESSMENT',userId:'user-1'});assert.equal(state.phase,'ERROR');assert.equal(state.error,'CHECKPOINT_WRITE_FAILED');assert.equal(state.offerVisible,false);});

test('journey persists safe checkpoints at every resumable milestone',async()=>{const checkpoints=[];const j=createP01FreeJourney(createDeps({journeyCheckpoint:{save:async({userId,state})=>{checkpoints.push({userId,phase:state.phase,lesson:state.currentLessonCode,stage:state.lessonState?.currentStage});return {id:'c-'+checkpoints.length,state_version:checkpoints.length};},loadLatest:async()=>null}}));await j.dispatch({type:'CONFIRM_ADULT_CONSENT',input:{allowed:true}});await j.dispatch({type:'START_ASSESSMENT',userId:'user-1'});await j.dispatch({type:'ANSWER_ASSESSMENT',input:{code:'P01Q01',value:4,complete:true},userId:'user-1'});await j.dispatch({type:'BUILD_CONTROL_MAP',userId:'user-1'});await j.dispatch({type:'START_L01',lesson:{},userId:'user-1'});await j.dispatch({type:'ADVANCE_L01',input:{final:false,nextStage:'PRACTICE'},userId:'user-1'});await j.dispatch({type:'SAVE_REFLECTION',privateRecord:{kind:'L01'},userId:'user-1'});assert.deepEqual(checkpoints.map(x=>x.phase),['ASSESSMENT','L01','L01','MAP_UPDATE']);assert.equal(checkpoints[2].stage,'PRACTICE');assert.equal(checkpoints.at(-1).lesson,'P01-L01');});

test('checkpoint persistence failure fails closed on a lesson milestone',async()=>{const j=createP01FreeJourney(createDeps({journeyCheckpoint:{loadLatest:async()=>null,save:async()=>{throw new Error('CHECKPOINT_WRITE_FAILED');}}}));await j.dispatch({type:'CONFIRM_ADULT_CONSENT',input:{allowed:true}});await j.dispatch({type:'START_ASSESSMENT',userId:'user-1'});await j.dispatch({type:'ANSWER_ASSESSMENT',input:{code:'P01Q01',value:4,complete:true}});await j.dispatch({type:'BUILD_CONTROL_MAP',userId:'user-1'});const state=await j.dispatch({type:'START_L01',lesson:{},userId:'user-1'});assert.equal(state.phase,'ERROR');assert.equal(state.error,'CHECKPOINT_WRITE_FAILED');assert.equal(state.offerVisible,false);});

test('bootstrap recovery failure fails closed',async()=>{const j=createP01FreeJourney(createDeps({journeyCheckpoint:{save:async()=>({}),loadLatest:async()=>{throw new Error('CHECKPOINT_READ_FAILED');}}}));const state=await j.dispatch({type:'BOOTSTRAP_SESSION',userId:'u'});assert.equal(state.phase,'ERROR');assert.equal(state.error,'CHECKPOINT_READ_FAILED');});

test('invalid consent blocks private assessment start',async()=>{const j=createP01FreeJourney(createDeps());const state=await j.dispatch({type:'CONFIRM_ADULT_CONSENT',input:{allowed:false}});assert.equal(state.phase,'BLOCKED');});
