export function createP01FreeJourney(deps = {}) {
  const { consentGate, assessment, controlMap, lesson, safety, recommendation, entitlement, practiceRuntime, controlMapHistory, journeyCheckpoint, analytics } = deps;
  if (!consentGate || !assessment || !controlMap || !lesson || !safety || !recommendation || !entitlement || !practiceRuntime || !controlMapHistory?.saveSnapshot || !controlMapHistory?.loadLatestSnapshot || !journeyCheckpoint?.save || !journeyCheckpoint?.loadLatest) throw new Error('P01_DEPENDENCIES_REQUIRED');
  let state={phase:'ENTRY',checkpointVersion:0,assessmentState:null,controlMap:null,lessonState:null,currentLessonCode:null,completedLessons:[],reflections:[],nextStep:null,safetyGuidance:null,offerVisible:false,offerAccess:null,practiceState:null,mapHistory:[],freeValueDelivered:false,error:null};
  const emit=(name,input)=>analytics?.(name,input);
  const requirePhase=p=>{if(state.phase!==p)throw new Error(`INVALID_P01_PHASE:${p}`);};
  const persist=async(userId)=>{if(!userId)return;const expectedVersion=state.checkpointVersion??0;const nextVersion=expectedVersion+1;const checkpoint=await journeyCheckpoint.save({userId,expectedVersion,state:structuredClone({...state,checkpointVersion:nextVersion,offerVisible:false})});state={...state,checkpointVersion:checkpoint?.state_version??checkpoint?.stateVersion??nextVersion};};
  const transition=async(next,userId)=>{const previous=state;state=next;try{await persist(userId);}catch(error){state=previous;throw error;}};

  return { getState:()=>structuredClone(state), async dispatch(event={}){ try { switch(event.type){
    case 'BOOTSTRAP_SESSION':{requirePhase('ENTRY');if(!event.userId)throw new Error('USER_ID_REQUIRED');const checkpoint=await journeyCheckpoint.loadLatest({userId:event.userId});if(checkpoint?.state){const recovered=checkpoint.state;if(!recovered.phase||recovered.phase==='ERROR'||recovered.offerVisible||recovered.phase==='OFFER')throw new Error('INVALID_JOURNEY_CHECKPOINT');state={...state,...recovered,checkpointVersion:checkpoint.stateVersion??recovered.checkpointVersion??0,offerVisible:false,error:null};emit('journey_checkpoint_recovered',{phase:state.phase,version:state.checkpointVersion});break;}const latest=await controlMapHistory.loadLatestSnapshot({userId:event.userId});if(!latest)break;if(!latest.map||latest.map.status!=='COMPLETE')throw new Error('INVALID_RECOVERED_MAP');state={...state,controlMap:latest.map,freeValueDelivered:true,mapHistory:[{version:latest.version??latest.map.version??1,status:'RECOVERED',id:latest.id??null}],phase:'NEXT_STEP',offerVisible:false,error:null};break;}
    case 'CONFIRM_ADULT_CONSENT':{requirePhase('ENTRY');const d=consentGate(event.input);if(!d.allowed){state={...state,phase:'BLOCKED',error:d.reason};break;}state={...state,phase:'ASSESSMENT',error:null};emit('assessment_started',{});break;}
    case 'START_ASSESSMENT':requirePhase('ASSESSMENT');{const next={...state,assessmentState:assessment.start(event.input)};await transition(next,event.userId);}break;
    case 'ANSWER_ASSESSMENT':requirePhase('ASSESSMENT');{const assessmentState=assessment.answer(state.assessmentState,event.input);const next={...state,assessmentState,phase:assessmentState.status==='COMPLETE'?'CONTROL_MAP':state.phase};await transition(next,event.userId);}break;
    case 'BUILD_CONTROL_MAP':{requirePhase('CONTROL_MAP');const map=controlMap.build(event.input);if(map.status!=='COMPLETE'){state={...state,controlMap:map};break;}const saved=await controlMapHistory.saveSnapshot({userId:event.userId,assessmentId:event.assessmentId??state.assessmentState?.assessmentId,instrumentVersion:state.assessmentState?.instrumentVersion??'1.0.0',map});await transition({...state,controlMap:map,freeValueDelivered:true,mapHistory:[{version:map.version??1,status:'SAVED',id:saved?.id??null}],phase:'L01'},event.userId);break;}
    case 'START_L01':{requirePhase('L01');await transition({...state,lessonState:lesson.create(event.lesson),currentLessonCode:'P01-L01'},event.userId);break;}
    case 'ADVANCE_L01':{requirePhase('L01');const lessonState=lesson.advance(state.lessonState,event.input);const next={...state,lessonState,completedLessons:lessonState.status==='COMPLETE'?[...state.completedLessons,'P01-L01']:state.completedLessons,phase:lessonState.status==='COMPLETE'?'REFLECTION':state.phase};await transition(next,event.userId);break;}
    case 'SAVE_REFLECTION':{requirePhase('REFLECTION');await transition({...state,reflections:[...state.reflections,{lessonCode:state.currentLessonCode,record:event.privateRecord}],phase:'MAP_UPDATE'},event.userId);break;}
    case 'UPDATE_MAP':{requirePhase('MAP_UPDATE');let phase;if(state.currentLessonCode==='P01-L01')phase='L02';else if(state.currentLessonCode==='P01-L02')phase='NEXT_STEP';else throw new Error('UNKNOWN_P01_LESSON');await transition({...state,controlMap:event.controlMap,phase},event.userId);break;}
    case 'START_L02':{requirePhase('L02');await transition({...state,lessonState:lesson.create(event.lesson),currentLessonCode:'P01-L02'},event.userId);break;}
    case 'ADVANCE_L02':{requirePhase('L02');const lessonState=lesson.advance(state.lessonState,event.input);const next={...state,lessonState,completedLessons:lessonState.status==='COMPLETE'?[...state.completedLessons,'P01-L02']:state.completedLessons,phase:lessonState.status==='COMPLETE'?'REFLECTION':state.phase};await transition(next,event.userId);break;}
    case 'RESOLVE_NEXT_STEP':{requirePhase('NEXT_STEP');const sr=safety.evaluate(event.safetyInput??{});if(sr.escalated){await transition({...state,safetyGuidance:sr,phase:'SAFETY_GUIDANCE',freeValueDelivered:true},event.userId);break;}const next=recommendation.next({controlMap:state.controlMap,safetyDecision:sr,...(event.recommendationInput??{})});await transition({...state,nextStep:next,practiceState:practiceRuntime.create({recommendation:next,safetyDecision:sr}),phase:'PRACTICE',offerVisible:false},event.userId);break;}
    case 'START_PRACTICE':{requirePhase('PRACTICE');await transition({...state,practiceState:state.practiceState.start()},event.userId);break;}
    case 'COMPLETE_PRACTICE':{requirePhase('PRACTICE');await transition({...state,practiceState:state.practiceState.complete(event.input??{}),phase:'PRACTICE_RESULT',offerVisible:false},event.userId);break;}
    case 'SAVE_PRACTICE_RESULT':{requirePhase('PRACTICE_RESULT');if(!event.privateRecord)throw new Error('PRACTICE_RECORD_REQUIRED');await transition({...state,reflections:[...state.reflections,{lessonCode:'PRACTICE',record:event.privateRecord}],phase:'MAP_UPDATE'},event.userId);break;}
    case 'UPDATE_PRACTICE_MAP':{requirePhase('MAP_UPDATE');const map=event.controlMap;const saved=await controlMapHistory.saveSnapshot({userId:event.userId,assessmentId:event.assessmentId??state.assessmentState?.assessmentId,instrumentVersion:state.assessmentState?.instrumentVersion??'1.0.0',map});state={...state,controlMap:map,mapHistory:[...state.mapHistory,{version:map.version??2,status:'SAVED',id:saved?.id??null}],phase:'OFFER',offerVisible:true};break;}
    case 'VIEW_OFFER':{if(state.phase!=='OFFER'){if(state.phase==='SAFETY_GUIDANCE')break;throw new Error('INVALID_P01_PHASE:OFFER');}const access=entitlement.evaluate({...event.entitlementInput,safetyDecision:state.safetyGuidance});state={...state,offerVisible:access.allowed||event.showOffer===true,offerAccess:access};break;}
    default:throw new Error('UNKNOWN_P01_EVENT');}
  }catch(error){state={...state,phase:'ERROR',offerVisible:false,error:error instanceof Error?error.message:String(error)};}return this.getState();} };
}
